# Generated by Django 5.1.2 on 2024-10-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_login_view_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
